services:
  # -------------------------------------
  # PostgreSQL
  # -------------------------------------
  postgres:
    image: postgres:17
    container_name: psql_source
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     PGADMIN_CONFIG_SERVER_MODE: "False"
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #       restart: true

  # -------------------------------------
  # ClickHouse
  # -------------------------------------
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: ch_analytics
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_PASSWORD=value
      # - PG_HOST=postgres
      # - PG_DB=postgres
      # - PG_USER=postgres
      # - PG_PASS=postgres
    depends_on:
      flyway:
        condition: service_completed_successfully
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      # this doesn't work some reason https://hub.docker.com/r/clickhouse/clickhouse-server
      # - ./clickhouse_init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 5s
      retries: 5
    links:
      - postgres:postgres

  python_sync:
    build:
      context: .
      dockerfile: Dockerfile.sync
    container_name: python_sync
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      clickhouse:
        condition: service_healthy
        restart: true
    volumes:
      - ./clickhouse_init.sql:/clickhouse_init.sql
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=value
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SLEEP_INTERVAL=10

  # -------------------------------------
  # Flyway Migrations
  # -------------------------------------
  flyway:
    image: flyway/flyway
    container_name: db_migrations
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    command: -url=jdbc:postgresql://postgres:5432/postgres -user=postgres -locations=filesystem:/flyway/sql migrate
    volumes:
      - ./migrations/:/flyway/sql
    environment:
      FLYWAY_CONNECT_RETRIES: 10
  # ERROR: No JDBC driver found to handle jdbc:clickhouse://clickhouse:8123/default. See <link> for troubleshooting
  # It seems like by default Flyway does not include the ClickHouse JDBC driver. To much work to get it working.
  # # -------------------------------------
  # # Flyway Migrations for ClickHouse
  # # -------------------------------------
  # flyway-clickhouse:
  #   image: flyway/flyway
  #   container_name: ch_migrations
  #   depends_on:
  #     clickhouse:
  #       condition: service_healthy
  #       restart: true
  #     flyway:
  #       condition: service_completed_successfully
  #   command: -url=jdbc:clickhouse://clickhouse:8123/default -user=default -password=value -locations=filesystem:/flyway/sql/clickhouse migrate
  #   volumes:
  #     - ./clickhouse-migrations/:/flyway/sql/clickhouse

volumes:
  postgres_data:
  clickhouse_data: